"""
NOPAINNOGAIN - Configuration Settings
"""

from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class SimulationConfig:
    GRID_WIDTH: int = 50
    GRID_HEIGHT: int = 50
    MAX_STEPS: int = 5000
    FPS: int = 30


@dataclass(frozen=True)
class PopulationConfig:
    INITIAL_PREY_POPULATION: int = 80
    INITIAL_PREDATOR_POPULATION: int = 12
    INITIAL_RESOURCE_COUNT: int = 500
    VICTORY_POPULATION: int = 500
    MIN_PREDATOR_POPULATION: int = 4
    MAX_PREDATOR_POPULATION: int = 30


@dataclass(frozen=True)
class AgentConfig:
    MAX_HEALTH: int = 100
    MAX_ENERGY: int = 100
    MIN_ENERGY: int = 0
    MAX_AGE: int = 150
    ENERGY_LOSS_PER_STEP: float = 0.5
    ENERGY_LOSS_PER_MOVE: float = 1.0
    REPRODUCTION_ENERGY_THRESHOLD: float = 70.0
    REPRODUCTION_ENERGY_COST: float = 30.0


@dataclass(frozen=True)
class PredatorConfig:
    ATTACK_DAMAGE: float = 40.0
    ATTACK_ENERGY_COST: float = 8.0
    HUNT_ENERGY_COST: float = 1.0
    MEAT_ENERGY_GAIN: float = 60.0
    VISION_RANGE: int = 6
    ATTACK_RANGE: int = 1
    HUNT_SUCCESS_BASE: float = 0.8
    METABOLISM_MULTIPLIER: float = 1.1


@dataclass(frozen=True)
class PreyConfig:
    FLEE_ENERGY_COST: float = 2.0
    FLEE_SPEED_BONUS: float = 1.5
    VISION_RANGE: int = 4
    FLEE_SUCCESS_BASE: float = 0.5


@dataclass(frozen=True)
class GeneticConfig:
    GENOME_LENGTH: int = 10
    MUTATION_RATE: float = 0.08
    MUTATION_STRENGTH: float = 1.5
    GENETIC_DISTANCE_THRESHOLD: float = 4.0
    SPECIATION_THRESHOLD: float = 6.0


@dataclass(frozen=True)
class ReinforcementLearningConfig:
    LEARNING_RATE: float = 0.15
    DISCOUNT_FACTOR: float = 0.95
    MAX_EXPLORATION_RATE: float = 1.0
    MIN_EXPLORATION_RATE: float = 0.05
    EXPLORATION_DECAY: float = 0.995
    ELIGIBILITY_DECAY: float = 0.9
    USE_ELIGIBILITY_TRACES: bool = True
    MEMORY_SIZE: int = 1000
    BATCH_SIZE: int = 32


@dataclass(frozen=True)
class ResourceConfig:
    MAX_RESOURCE_CAPACITY: int = 100
    PLANT_NUTRITIONAL_VALUE: int = 25
    WATER_NUTRITIONAL_VALUE: int = 15
    MINERAL_NUTRITIONAL_VALUE: int = 8
    PLANT_REGEN_RATE: float = 2.0
    WATER_REGEN_RATE: float = 3.0
    MINERAL_REGEN_RATE: float = 0.5


@dataclass(frozen=True)
class RewardConfig:
    REWARD_EAT_SUCCESS: float = 10.0
    REWARD_DRINK_SUCCESS: float = 5.0
    REWARD_MOVE_TO_RESOURCE: float = 2.0
    PENALTY_MOVE_TO_HAZARD: float = -3.0
    PENALTY_FAILED_ACTION: float = -1.0
    PENALTY_DEATH: float = -50.0
    REWARD_REPRODUCTION: float = 20.0
    REWARD_SUCCESSFUL_HUNT: float = 30.0
    REWARD_SUCCESSFUL_ATTACK: float = 25.0
    REWARD_SUCCESSFUL_FLEE: float = 15.0
    PENALTY_FAILED_HUNT: float = -5.0
    PENALTY_ATTACKED: float = -20.0
    REWARD_SURVIVAL: float = 1.0
    PENALTY_NEAR_PREDATOR: float = -5.0
    REWARD_NEAR_PREY: float = 3.0


@dataclass(frozen=True)
class EnvironmentConfig:
    HAZARD_BASE_LEVEL: int = 3
    MAX_HAZARD_VALUE: int = 10
    POLLUTION_DECAY_RATE: float = 0.5


@dataclass(frozen=True)
class VisualizationConfig:
    SCREEN_WIDTH: int = 1000
    SCREEN_HEIGHT: int = 1000
    TILE_SIZE: int = 20
    SHOW_HEALTH_BARS: bool = True
    SHOW_ENERGY_INDICATOR: bool = True


COLORS: Dict[str, Tuple[int, int, int]] = {
    "background": (15, 15, 25),
    "grid_line": (40, 40, 55),
    "ground": (30, 30, 40),
    "resource_plant": (34, 139, 34),
    "resource_water": (65, 105, 225),
    "resource_mineral": (169, 169, 169),
    "hazard": (180, 50, 50),
    "prey": (255, 215, 0),
    "predator": (220, 20, 60),
    "horns": (255, 255, 255),
    "death_particle": (255, 100, 100),
    "birth_particle": (100, 255, 100),
    "attack_particle": (255, 50, 50),
    "flee_particle": (100, 200, 255),
    "hunt_particle": (255, 140, 0),
    "health_bar_bg": (60, 60, 60),
    "health_bar_full": (50, 205, 50),
    "health_bar_low": (220, 20, 60),
    "energy_bar_full": (30, 144, 255),
    "energy_bar_low": (255, 140, 0),
}


SIM = SimulationConfig()
POP = PopulationConfig()
AGENT = AgentConfig()
PREDATOR = PredatorConfig()
PREY = PreyConfig()
GENETIC = GeneticConfig()
RL = ReinforcementLearningConfig()
RESOURCE = ResourceConfig()
REWARD = RewardConfig()
ENV = EnvironmentConfig()
VIS = VisualizationConfig()

GRID_WIDTH = SIM.GRID_WIDTH
GRID_HEIGHT = SIM.GRID_HEIGHT
MAX_STEPS = SIM.MAX_STEPS
FPS = SIM.FPS
INITIAL_PREY_POPULATION = POP.INITIAL_PREY_POPULATION
INITIAL_PREDATOR_POPULATION = POP.INITIAL_PREDATOR_POPULATION
INITIAL_RESOURCE_COUNT = POP.INITIAL_RESOURCE_COUNT
VICTORY_POPULATION = POP.VICTORY_POPULATION
MAX_HEALTH = AGENT.MAX_HEALTH
MAX_ENERGY = AGENT.MAX_ENERGY
MIN_ENERGY = AGENT.MIN_ENERGY
MAX_AGE = AGENT.MAX_AGE
ENERGY_LOSS_PER_MOVE = AGENT.ENERGY_LOSS_PER_MOVE
REPRODUCTION_ENERGY_THRESHOLD = AGENT.REPRODUCTION_ENERGY_THRESHOLD
REPRODUCTION_ENERGY_COST = AGENT.REPRODUCTION_ENERGY_COST
GENOME_LENGTH = GENETIC.GENOME_LENGTH
MUTATION_RATE = GENETIC.MUTATION_RATE
MUTATION_STRENGTH = GENETIC.MUTATION_STRENGTH
GENETIC_DISTANCE_THRESHOLD = GENETIC.GENETIC_DISTANCE_THRESHOLD
SPECIATION_THRESHOLD = GENETIC.SPECIATION_THRESHOLD
LEARNING_RATE = RL.LEARNING_RATE
DISCOUNT_FACTOR = RL.DISCOUNT_FACTOR
MAX_EXPLORATION_RATE = RL.MAX_EXPLORATION_RATE
MIN_EXPLORATION_RATE = RL.MIN_EXPLORATION_RATE
EXPLORATION_DECAY = RL.EXPLORATION_DECAY
MAX_RESOURCE_CAPACITY = RESOURCE.MAX_RESOURCE_CAPACITY
PLANT_NUTRITIONAL_VALUE = RESOURCE.PLANT_NUTRITIONAL_VALUE
WATER_NUTRITIONAL_VALUE = RESOURCE.WATER_NUTRITIONAL_VALUE
MINERAL_NUTRITIONAL_VALUE = RESOURCE.MINERAL_NUTRITIONAL_VALUE
PLANT_REGEN_RATE = RESOURCE.PLANT_REGEN_RATE
WATER_REGEN_RATE = RESOURCE.WATER_REGEN_RATE
MINERAL_REGEN_RATE = RESOURCE.MINERAL_REGEN_RATE
REWARD_GATHER = REWARD.REWARD_EAT_SUCCESS
REWARD_MOVE_TO_RESOURCE = REWARD.REWARD_MOVE_TO_RESOURCE
PENALTY_MOVE_TO_HAZARD = REWARD.PENALTY_MOVE_TO_HAZARD
PENALTY_FAILED_ACTION = REWARD.PENALTY_FAILED_ACTION
PENALTY_DEATH = REWARD.PENALTY_DEATH
HAZARD_BASE_LEVEL = ENV.HAZARD_BASE_LEVEL
MAX_HAZARD_VALUE = ENV.MAX_HAZARD_VALUE
SCREEN_WIDTH = VIS.SCREEN_WIDTH
SCREEN_HEIGHT = VIS.SCREEN_HEIGHT
TILE_SIZE = VIS.TILE_SIZE

ATTACK_DAMAGE = PREDATOR.ATTACK_DAMAGE
ATTACK_ENERGY_COST = PREDATOR.ATTACK_ENERGY_COST
HUNT_ENERGY_COST = PREDATOR.HUNT_ENERGY_COST
MEAT_ENERGY_GAIN = PREDATOR.MEAT_ENERGY_GAIN
PREDATOR_VISION_RANGE = PREDATOR.VISION_RANGE
PREY_VISION_RANGE = PREY.VISION_RANGE
FLEE_ENERGY_COST = PREY.FLEE_ENERGY_COST
FLEE_SPEED_BONUS = PREY.FLEE_SPEED_BONUS
